#page title
page_title                                : Nighthawk Wallet                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1524708337                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
fdroid_link                               : https://f-droid.org/en/packages/com.nighthawkapps.wallet.android/                                        
playstore_link                            : https://play.google.com/store/apps/details?id=com.nighthawkapps.wallet.android
presskit_download_link                    : https://www.nighthawkwallet.com/assets/presskit.zip

app_icon                                  : assets/android-chrome-192x192.png         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Nighthawk Wallet                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Private Money in your pocket.             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Nighthawk no longer supports outgoing ZEC transactions, after the recent network upgrade. To access your funds, you will need to import your wallet seed to other dedicated Zcash wallets, such as Zashi or Zingo

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name                                 : Nighthawk Apps                     
your_link                                 : https://nighthawkapps.com/
your_city                                 :                                 
email_address                             : nighthawkwallet@protonmail.com
facebook_username                         :  
instagram_username                        : NighthawkWallet                                          
twitter_username                          : NighthawkWallet
github_username                           : nighthawk-apps
youtube_username                          :

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Spend with Flexa
    description                           : Spend your crypto at 10,000+ locations across the US âœ¨
    fontawesome_icon_name                 : magic

  - title                                 : Nighthawk is a light-wallet
    description                           : Requires trust in the lightwalletd server for displaying accurate transaction information.
    fontawesome_icon_name                 : sync

  - title                                 : Self-custody wallet
    description                           : Take sole responsibility for your funds on Nighthawk. Securely backup seed words immediately.
    fontawesome_icon_name                 : star

  - title                                 : PIN protection
    description                           : Set a 6 digit pin and even enable Face Id/Touch Id to open the wallet.
    fontawesome_icon_name                 : mobile

  - title                                 : Unstoppable Domains Support
    description                           : Opt-in UNS support under Settings > External Services for worry-free ZEC transactions.
    fontawesome_icon_name                 : mobile

  - title                                 : Backup Seed Words to PDF
    description                           : Securely generate a password-protected PDF with wallet seed words.
    fontawesome_icon_name                 : arrow-alt-circle-down

# Theme Settings
topbar_color                              : "#110e2b"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#413e55"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#2e90e9"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#413e55"

feature_icons_foreground_color            : "#2e90e9"
feature_icons_background_color            : "#e7e7ea"

social_icons_foreground_color             : "#413e55"
social_icons_background_color             : "#e7e7ea"

footer_text_color                         : "#a09faa"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
